# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1dd16e1a20803f4fc04f9ed2250305df262d16ff658b54eb33c2aee1109aef4fbdadb2f3f5e6c6ec70df38d68e4e5f00ab2ef92fb803123f59c2e2cd9ab5c2

test:
  secret_key_base: 648fe3d54a25d8880455f7b43a051633487da36b8dc9c34a0a520b778a47a87089cc8e0de88db7e7b8af17432d4a181d6f21cc13e392d8e5766b12a3c2a01def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
